version: "3"
   
services:
  sicei_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sicei
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    networks: 
      - sicei_connect
  sicei_api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - sicei_db 
    links:        
      - sicei_db
    networks: 
      - sicei_connect
networks:
  sicei_connect:
    driver: bridge